In [3]:
from __future__ import print_function
import torch

In [4]:
x = torch.empty(5,3)
print(x)

tensor([[6.6633e-33, 4.3612e+27, 8.7518e-04],
        [1.1692e-19, 1.5637e-01, 1.3000e+34],
        [5.0782e+31, 4.2964e+24, 1.7443e+28],
        [2.5318e-12, 8.1470e-33, 1.3563e-19],
        [1.6114e-19, 1.3556e-19, 7.2053e+22]])


In [5]:
y = torch.zeros(5, 3, dtype=torch.float)
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [6]:
print(x + y)

tensor([[6.6633e-33, 4.3612e+27, 8.7518e-04],
        [1.1692e-19, 1.5637e-01, 1.3000e+34],
        [5.0782e+31, 4.2964e+24, 1.7443e+28],
        [2.5318e-12, 8.1470e-33, 1.3563e-19],
        [1.6114e-19, 1.3556e-19, 7.2053e+22]])


In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
y[:, 1:3]

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [9]:
y.numpy()

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [10]:
z = torch.ones(5,3, requires_grad=True)

In [14]:
k = (z * z).sum()
print(k)

tensor(15., grad_fn=<SumBackward0>)


In [15]:
print(k.requires_grad)

True


In [16]:
print(k.grad_fn, k.grad)
k.backward()
print(k.grad_fn, k.grad)

<SumBackward0 object at 0x7f41d685c310> None
<SumBackward0 object at 0x7f41d685c310> None


In [17]:
print(x.grad)

None
