In [9]:
from __future__ import print_function
import torch

In [10]:
x = torch.empty(5,3)
print(x)

tensor([[1.6079e-08, 4.5745e-41, 1.9199e-36],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 7.2646e+22, 7.2250e+28],
        [2.5226e-18, 2.4283e-18, 2.6302e+20]])


In [11]:
y = torch.zeros(5, 3, dtype=torch.float)
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [12]:
print(x + y)

tensor([[1.6079e-08, 4.5745e-41, 1.9199e-36],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 7.2646e+22, 7.2250e+28],
        [2.5226e-18, 2.4283e-18, 2.6302e+20]])


In [13]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [14]:
y[:, 1:3]

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [15]:
y.numpy()

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [16]:
z = torch.ones(5,3, requires_grad=True)

In [17]:
k = (z * z).sum()
print(k)

tensor(15., grad_fn=<SumBackward0>)


In [18]:
print(k.requires_grad)

True


In [19]:
print(k.grad_fn, k.grad)
k.backward()
print(k.grad_fn, k.grad)

<SumBackward0 object at 0x7f84a9dd4be0> None
<SumBackward0 object at 0x7f84a9dd4be0> None


/usr/lib/python3/dist-packages/ipykernel_launcher.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  """Entry point for launching an IPython kernel.
/usr/lib/python3/dist-packages/ipykernel_launcher.py:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  This is sepa

In [21]:
print(k.grad)

None


/usr/lib/python3/dist-packages/ipykernel_launcher.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  """Entry point for launching an IPython kernel.
